import './globals.scss'
import { Inter } from 'next/font/google'
import Navbar from './components/Navbar'
import { Providers } from './redux/Provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Task manager',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, modal }) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Navbar/>
          {children}
          {modal}
        </Providers>
      </body>
    </html>
  )
}
